jobs:
  - name: rr-1
    type: manifest
    steps:
      - IN: rrimg-1
      #- IN: rrimg2
      - IN: trigger-dv-man-1
      - TASK: managed

  # - name: jatin-2
  #   type: manifest
  #   steps:
  #     - GET: box-sn
  #     - GET: trigger-dv-man

  # - name: ecs-deploy
  #   type: ecsDeploy
  #   options:
  #     deployMethod: blueGreen
  #   steps:
  #     - GET: jatin-1
  #     - GET: jatin-2
  #     - GET: ecs-cluster

  # - name: tri-deploy
  #   type: tripubDeploy
  #   options:
  #     deployMethod: upgrade
  #   steps:
  #     - GET: box-man-1
  #     - GET: tri-cluster

  #- name: gkeDeploy
   # type: gkeDeploy
   # steps:
    #  - GET: jD-1
    #  - GET: gke-cluster
    #  - TASK: managed
    #    deployMethod: upgrade

  # - name: ddc-deploy
  #   type: ddcDeploy
  #   steps:
  #     - GET: box-man-1
  #     - GET: ddc-cluster

  # - name: dcl-deploy
  #   type: dclDeploy
  #   steps:
  #     - GET: box-man-1
  #     - GET: dcl-cluster
