triggers:
   - name: sh-trigger
     type: trigger
     pointer:
       counter: 100

   - name: releaseTrigger
     type: trigger
     version:
       message: '2q22qreate a AArelease from staging cluster. triggered:1'