jobs:
  - name: sh-manifestjob1
    type: manifest
    steps:
      - IN: sh-myapp2
      #- IN: sh-docker-opts
      - IN: sh-trigger
      #- IN: sh-lb-1

  # - name: sh-ecsDeploy
  #   type: deploy
  #   steps:
  #     - IN: sh-manifestjob1
  #     - IN: sh-ecs-cluster
  #     - IN: sh-lb-2
  #       applyTo:
  #         - manifest: sh-manifestjob1 # it can only apply to one manifest
  #           image: sh-myapp3 # it can only apply to one image in the manifest
  #           port: 80
  #     - TASK: managed
  #       deployMethod: upgrade
  - name: tri-deploy123
    type: deploy
    steps:
      - IN: sh-manifestjob1
      #- IN: manifestjob2
      - IN: tri-cluster
      - TASK: managed
        deployMethod: upgrade

  # - name: sample
  #   type: runSh
  #   steps:
  #     - IN: sample_node
  #   on_success:
  #     - script: echo 'This block executes after TASK section executes successfully'

  # # - name: gke-deploy
  #   type: deploy
  #   steps:
  #     - IN: manifestjob1
  #     - IN: scale
  #     - IN: gkecluster
  # - name: dcl-deploy
  #   type: dclDeploy
  #   steps:
  #     - GET: box-man-1
  #     - GET: dcl-cluster

    # - name: jatin-2
  #   type: manifest
  #   steps:
  #     - GET: box-sn
  #     - GET: trigger-dv-man

  # - name: ecs-deploy
  #   type: ecsDeploy
  #   options:
  #     deployMethod: blueGreen
  #   steps:
  #     - GET: jatin-1
  #     - GET: jatin-2
  #     - GET: ecs-cluster

  # - name: tri-deploy
  #   type: tripubDeploy
  #   options:
  #     deployMethod: upgrade
  #   steps:
  #     - GET: box-man-1
  #     - GET: tri-cluster

  #- name: gkeDeploy
   # type: gkeDeploy
   # steps:
    #  - GET: jD-1
    #  - GET: gke-cluster
    #  - TASK: managed
    #    deployMethod: upgrade

  # - name: ddc-deploy
  #   type: deploy
  #   steps:
  #     - IN: manifestjob1
  #     - IN: ddc-cluster

  # - name: tri-deploy
  #   type: deploy
  #   steps:
  #     - IN: manifestjob1
  #     - IN: manifestjob2
  #     - IN: tri-cluster
  #     # - TASK: managed
  #     #   deployMethod: upgrade

